setup:
  ansible: .trousers/setup.playbook.yml
teardown:
  ansible: .trousers/cleanup.playbook.yml
checks:
  screenshots:
    url: http://localhost:9000/uk
  exceptions:
    url: http://localhost:9000/uk
reporting:
  github: .trousers/github_comment.template
